jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: ubuntu-20.04
  steps:
  - checkout: self
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: react-app/
      verbose: false
  - task: Npm@1
    displayName: npm run build
    inputs:
      command: custom
      workingDir: react-app/
      verbose: false
      customCommand: run build
  - task: CmdLine@2
    displayName: Command Line Script
    inputs:
      script: mv react-app/build WebAPI/wwwroot
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: WebAPI/WebAPI/WebAPI.csproj
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      projects: WebAPI/WebAPI/WebAPI.csproj.csproj
  - task: DotNetCoreCLI@2
    displayName: dotnet publish
    inputs:
      command: publish
      projects: WebAPI/WebAPI/WebAPI.csproj.csproj
      arguments: -c Release -o $(Build.ArtifactStagingDirectory)/publish
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: react-demo-backend'
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)/publish
      ArtifactName: react-demo-backend